version: '3'
services:
  webserver:
    container_name: webserver
    image: dinaerteneto/docker-laravel
    volumes:
      - ./app:/app:cached
    links:
      - mysql
    ports:
      - 80:80

  mailcatcher:
    container_name: mailcatcher
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025       

  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - ./database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    ports:
      - 3306:3306